apiVersion: apps/v1

kind: Deployment

metadata:
  name: custbff
  namespace: book-store-ns

spec:
  selector:
    matchLabels:
      run: custbff

  replicas: 1

  template:
    metadata:
      labels:
        run: custbff

    spec:
      containers:
        - name: custbff

          image: aarushis/custbff:latest

          ports:
            - containerPort: 82
          livenessProbe:
            httpGet:
              path: /status
              port: 82
            initialDelaySeconds: 10
            periodSeconds: 30
          env:
            - name: BACKEND_HOST
              value: custsvc
            - name: BACKEND_PORT
              value: "3000"

---
apiVersion: v1
kind: Service
metadata:
  name: custbff
  namespace: book-store-ns
  labels:
    run: custbff
spec:
  ports:
    - port: 82
      targetPort: 82
      protocol: TCP
  selector:
    run: custbff
  type: LoadBalancer
